### PR TITLE
Updated files, added requirements.txt and updated installation instructions in README.md

### PR DESCRIPTION
**Pull request by shashankjangde**
**Hello @vinitshahdeo,**
- As per the updated Twitter API, **some methods have been deprecated**, so I've updated the code which has the updated methods.
- Removed all the hard-coded API keys which were present in the files of 'hashtag' subdirectory.
- Also, I have added requirements.txt so that the necessary libraries could be installed with one command and subsequently updated README.md with added installation instruction.

By the way, this is my first PR and also my first contribution to Open Source Projects. I would greatly appreciate constructive feedback and look forward to contributing value to even more projects in the future.😊

Regards.

### CODE REVIEW

**Review by vinitshahdeo — COMMENTED** [review]
Hey, thanks for the PR. Did you run it locally? Can you please share a loom recording?

**Comment by shashankjangde** [comment]
Thank You for the reply @vinitshahdeo 
Yes, I did run the code locally and got a few errors, which are the ones I resolved and committed to the forked copy of my repo. The only issue I was facing was with the API giving the error with code 453 which I later found out through various discussion on forums that when Twitter was acquired and later changed to X, the Developer Free tier also went through some changes due to which even pulling data from X using the API was not given access to the free tier users. And even for the basic access we need to buy the basic package which costs $100/month. Thus, I was unable to fully test the code, but I went through various discussions which led to my final conclusion that the rest of the code should be working correctly. I've attached relevant screenshots as well.

X API Plans
free tier

Also, please refer to this doc file in which I have attached the screenshot of the resolved issues:
https://docs.google.com/document/d/1R8U--17XPKwj3elAIpdurQkAy41kPxjv6J1zCW_ydQ0/edit?usp=sharing

I would greatly appreciate any kind of feedback which would help me grow. 😊

Also, I forgot to save the files before committing to the repository, which I noticed now, thus the search and the tweeperror method are still unchanged in the files inside the hashtags subdirectory. I'll commit the changes to my forked repo now.

PS: I've committed the changes to my forked repo.

**Comment by vinitshahdeo** [comment]
Thank you! Merging it to `develop`.

**Comment by shashankjangde** [comment]
Hey @vinitshahdeo 
Thanks a lot for approving the pull request. This PR approval not only made my day a lot better, but also made the start of my journey even more memorable and this journey even more exciting.😊

With this, I'm officially on the journey of being an open source contributor.
Thanks a lot!

**Comment by vinitshahdeo** [comment]
Thank you so much. Welcome to the open-source world.

All the best:)

**Pull request merged**
